services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: gunicorn curio4.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./server/src/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose: 
      - 8000
    env_file:
      - ./.env/dev.env

  frontend:
    build:
      context: ./client/react
      dockerfile: Dockerfile
    volumes:
      - react_build:/react/build
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
    - 80:8080
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - ./server/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: curio4_development
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./server/data/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

volumes:
  react_build:
  static_files:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
        - gateway: "192.168.0.0"

