# Generated by Django 5.0.6 on 2024-07-25 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='users.school'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.school'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.school'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.choice'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='users.school'),
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.studenttestsession'),
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.course'),
        ),
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.grade'),
        ),
        migrations.AddField(
            model_name='test',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.programme'),
        ),
        migrations.AddField(
            model_name='test',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.school'),
        ),
        migrations.AddField(
            model_name='test',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.term'),
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='questions.test'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.test'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttestsession',
            unique_together={('student', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question', 'test')},
        ),
    ]
