# Generated by Django 5.0.6 on 2024-07-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_test_school'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='users.school'),
        ),
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='users.school'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='users.school'),
        ),
        migrations.AlterField(
            model_name='studenttestsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='users.school'),
        ),
    ]
