name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Navigate to Django project directory
      run: cd server/src

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/src/requirements.txt

    - name: Run Django tests
      run: |
        cd server/src
        python manage.py test
