name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}   # It is used to select the os for the build. 
    strategy:
      max-parallel: 4           # It is used to set the maximum number of jobs that can run simultaneously.
      matrix:                   # It is used to declare a list of values for which the pipeline should work on. This can be used to create different workflows for different environments using one workflow. 
        python-version: [3.10, 3.11, 3.12]  # This lets me run the pipeline on different python versions.
        os: [ubuntu-latest] # This lets me run the pipeline on different OS versions.
       # os: [ubuntu-latest, windows-latest, macos-latest] # This lets me run the pipeline on different OS versions.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Super-Linter
      uses: github/super-linter@latest
      env:
        #VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Navigate to Django project directory
      run: cd server/src

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/src/requirements.txt

#    - name: Run Django tests
#      run: |
#        cd server/src
#        python manage.py test

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: sjokagyi/github_actions_tutorial_using_curio5
        tag: v1, latest
        registry: docker.io
        dockerfile: server/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}